checks:
  php: true

build:
  tests:
    override:
    -
      command: 'vendor/bin/phpunit --coverage-clover=clover'
      coverage:
        file: 'clover'
        format: 'clover'

  analysis:
    project_setup:
      override: true
    tests:
      override: [php-scrutinizer-run]

  nodes:
    php56:
      environment:
        php: 5.6

    php71:
      environment:
        php: 7.1

    php72:
      environment:
        php: 7.2

filter:
  paths: ["src/*"]