checks:
  php: true

filter:
  paths: ["src/*"]

build:
  tests:
    override:
    - php-scrutinizer-run
    -
      command: vendor/bin/phpunit --coverage-clover=coverage
      coverage:
        file: coverage
        format: clover

  cache:
    directories:
    - vendor/
    - ~/.composer/cache/

  nodes:
    php71:
      environment:
        php: 7.1

    php72:
      environment:
        php: 7.2
